# Generated by Django 5.2.6 on 2025-10-27 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0006_employee_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tolerance_in', models.IntegerField(default=15)),
                ('tolerance_out', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
