# Generated by Django 5.2.6 on 2025-10-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='tolerance_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='tolerance_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('name', 'start_time', 'end_time')},
        ),
    ]
