# Generated by Django 5.2.6 on 2025-10-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id_dept', models.AutoField(primary_key=True, serialize=False)),
                ('nama_dept', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
