# Generated by Django 5.2.6 on 2025-10-21 04:26

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_photo_breaklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employees/default.png', null=True, upload_to='employees/', validators=[employee.models.Employee.validate_image]),
        ),
    ]
