# Generated by Django 5.2.6 on 2025-10-22 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
        ('employee', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='dept.dept'),
        ),
    ]
