# Generated by Django 5.2.6 on 2025-10-22 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_dept'),
        ('jabatan', '0002_jabatan_kode_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jabatan.jabatan'),
        ),
    ]
