# Generated by Django 5.2.6 on 2025-10-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_pin',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
