# Generated by Django 5.2.6 on 2025-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_id_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_qr_attend',
            field=models.BooleanField(default=False, help_text='Jika True, karyawan ini bisa absen menggunakan QR Code'),
        ),
    ]
