# Generated by Django 5.2.6 on 2025-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='verify_mode',
            new_name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verify_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('machine', 'user_id', 'timestamp')},
        ),
    ]
