# Generated by Django 5.2.6 on 2025-10-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabatan',
            name='kode_jabatan',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
